### ISSUE TITLE
Unable o import TestImpacted class in gradle

### ISSUE THREAD

**Issue by Kanti1702** [cqse/teamscale-jacoco-agent#109]
While utilizing your teamscale-gradle-plugin I required to use TestImpacted class, but it givs below error:

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'TestImpacted' for root project

Below is my build.gradle:

> 
     buildscript {
	ext.kotlin_version = '1.3.61'
	repositories {
		jcenter()
	}
	repositories {
		mavenCentral()
		maven { url 'https://share.cqse.eu/public/maven/' }
	}
	dependencies {
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
		classpath 'com.teamscale:teamscale-gradle-plugin:0.4.14'
	}
     }

     apply plugin: 'kotlin'
     apply plugin: 'teamscale'

     teamscale {
	server {
		url = 'https://mycompany.com/teamscale/'
		userName = 'build'
		userAccessToken = '7fa5.....'
		project = 'example-project-id'
	}

	commit {
		branchName = 'master'
		timestamp = 1521800427000L // Timestamp in milliseconds
	}
	report {
		partition = 'Unit Tests'
		testwiseCoverage()
		googleClosureCoverage { js ->
			js.destination = files("$rootDir/engine/com.teamscale.test/ui-test-coverage")
			js.excludes = ["**/google-closure-library/**", "**.soy.generated.js", "soyutils_usegoog.js"]
		}
	}
      }

     repositories {
	mavenCentral()
     }

    dependencies {
	testImplementation('org.junit.jupiter:junit-jupiter:5.6.0')
    }

    test {
   	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
    }

    tasks.register('unitTest', TestImpacted) {
	useJUnitPlatform {
		excludeTags 'integration'
	}
	teamscale.report.partition = 'Unit Tests'
    }

Did I miss anything?

**Comment by karottenreibe** [comment]
Unfortunately, the documentation for this features is very much "work in progress" or some would say "wildly out of date" ;-)

In this particular case, you're missing an import for that class. You can e.g. fully qualify it with 

```
tasks.register('unitTest', com.teamscale.TestImpacted) {
...
}
```

**Comment by karottenreibe** [comment]
Please note that the Gradle code you copy-pasted has several other issues that you'll likely run into because it wasn't updated after the latest changes! We're working on that but it may be a while until it is fully up-to-date.
