### ISSUE TITLE
Dead link to TEST_IMPACT_ANALYSIS.md

### ISSUE THREAD

**Issue by sewe** [cqse/teamscale-jacoco-agent#148]
In https://github.com/cqse/teamscale-jacoco-agent/blob/master/agent/README.md there is a dead link to a `TEST_IMPACT_ANALYSIS.md`. I assume this should point to https://github.com/cqse/teamscale-jacoco-agent/blob/master/TEST_IMPACT_ANALYSIS_DOC.md.

**Comment by karottenreibe** [comment]
Migrated to https://jira.cqse.eu/browse/TS-23818 as we track issues there
