### ISSUE TITLE
Record testwise coverage without impacted test analysis

### ISSUE THREAD

**Issue by ole-ve** [cqse/teamscale-jacoco-agent#201]
## Current behavior
When recording the testwise coverage, the `--impacted` flag has to be set in order for the agent to record the coverage and save it to the corresponding report file. This requires a server configuration for a Teamscale server in the `build.gradle`.
However, the coverage recording works as expected with the `--impacted` flag, even if the configuration is not valid and references a server that does not exist. The plugin fails while trying to connect to the defined Teamscale server but the coverage output is as expected.

When the only point of using this plugin is to record testwise coverage, this network access would not be needed.

## Steps to Reproduce
1. Use the sample project from the [TIA documentation](https://docs.teamscale.com/tutorial/tia-java/#step-1-adding-the-teamscale-plugin).
2. Checkout to the step where the configuration has been completed: `git checkout origin/step2`. The configurated server in the `build.gradle` must not exist
3. Execute `./gradlew clean tiaTests --run-all-tests`
4. Confirm that the report file does not have any content, except for the test names and locations
5. Execute `./gradlew clean tiaTests --run-all-tests --impacted`
6. Confirm that the report file now contains all the expected data

## Proposed behavior
It would be great if the coverage could be recorded also without the impacted flag.

## Additional Context
We want to use this plugin (in particular the testwise coverage analysis) within the learning platform [Artemis](https://github.com/ls1intum/Artemis) from the TUM. In this context, all test cases are executed in a [custom sandbox](https://github.com/ls1intum/Ares) that restricts permission via the Security Manager. Disallowing network permissions by default is one of these restrictions. We would like to keep the allowed behavior as minimal as possible.

**Note**: I opened this issue on GitHub because I do not have access permission to JIRA.

**Comment by DreierF** [comment]
Thanks for the report!Should be fixed with #202.

**Comment by ole-ve** [comment]
Thanks, @DreierF for the very fast fix. I tested it locally and it works just as expected for me. Great work 👍
