### ISSUE TITLE
Investigate Timeout Error

### ISSUE THREAD

**Issue by DreierF** [cqse/teamscale-jacoco-agent#27]
The hypothesis was that this happens when the interval is e.g. set to 1 and the upload takes longer than 1 minute to succeed.

Quote:
Dieses ist wohl dadurch entstanden, dass ich das Intervall auf „1“ gesetzt hatte (da in der vorherigen Version des Agents „0“ nicht funktionierte). Dann haben sich beim Beenden von <system under test> wohl der „Shutdown“-Upload und der zyklische Upload überschnitten, was dann zur Timeout-Problematik geführt hat. Damit hatte ich vorhin mehrfache Uploads (in Teamscale kommen diese wohl an, nur der Client bekommt das Upload-Ende nicht mit).

**Comment by karottenreibe** [comment]
not a supported use-case. setting interval to 1 is only intended to be used for testing. Thus discarding this issue
