### ISSUE TITLE
Document Tomcat Windows Configuration

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#30]
When running Tomcat in Windows via the tomcat7.exe executable (either manually via double click or because it is run as a Windows service), it will not pick up changes made to the setenv.bat file. 

We should enhance the docs to cover that case: 

Changes need to be made in the Tomcat Configuration GUI program: Start > All Programs > Apache Tomcat > Tomcat Configuration.
In the Java tab, at the bottom of the Java Options field, append the -javaagent... parameter.

Also see https://serverfault.com/questions/79641/how-can-i-configure-tomcat-java-options-in-a-config-file on how to set that value from the command line.

**Comment by karottenreibe** [comment]
Migrated as TS-21143
