### ISSUE TITLE
Provide Troubleshooting Documentation

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#32]
We should add a few lines about common configuration issues and how to resolve them.

- No XML report: Enable Debug Logging
- No Log although logging enabled: Agent probably not attached. Check process command line / environment variables
- Log, but no XML: Check for filter messages. Adapt include / exclude patterns
- XML, but no coverage in Teamscale: Check for values other than `covered="0"` in the XML
- XML, but only `covered="0"` entries: `class-dir` possibly points to the wrong location / archive.

**Comment by karottenreibe** [comment]
Migrated as TS-21141
