### ISSUE TITLE
Increase in JVM memory footprint during dump

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#35]
Some users reported that their JVM memory was very tightly restricted to a little more than the application was known to consume. 

Attaching the agent blew that limit and caused OOM exceptions. 

We should mention that instrumentation does not come for free, but needs JVM memory in addition to a possible slowdown.

**Comment by agoeb** [comment]
Just learned the memory requirements come from the XML generation step. Maybe we can have a look into optimization potential there?

**Comment by karottenreibe** [comment]
@agoeb looking at JaCoCos XML report generation code I don't see any immediate potential for optimization. For now, I'd just document the requirement and leave any in-depth debugging for when this becomes an actual problem.

**Comment by agoeb** [comment]
Just saw that we hold the complete XML report in memory in a `ByteArrayOutputStream` and a `String` before writing it to disk or sending it to Teamscale. So there might be some potential, especially when the target is the disk. Not sure about how our upload code assembles the multi-part entities - these might create a third copy of the data before uploading. So I guess we might become more efficient there.

**Comment by karottenreibe** [comment]
@agoeb In order to be able to send the Length header, Retrofit needs to know the number of bytes in the report before we can send it. I.e. we can't directly stream to Teamscale because then we don't know the length. We'd have to serialize to disk first and then re-read it from there together with a correct length, unfortunately.

**Comment by agoeb** [comment]
Disk is not a problem either. So we could write the XML to disk without first constructing all the content as a String in memory. We might even write the bytes directly to disk, and upload afterwards, which would save quite some RAM, considering XML reports can be 20-100 MB in some cases.

**Comment by agoeb** [comment]
Some more insight looking at a heap dump during the creation of an XML report (which resulted in around 180MB).

![overview](https://user-images.githubusercontent.com/2226123/65264434-dae55b00-db0e-11e9-94a0-78ea79e83447.png)

While the whole Java process including the application server used up under 240 MB, the agent already consumed 380 MB, and this was before the conversion into a String.

![classes](https://user-images.githubusercontent.com/2226123/65264435-dae55b00-db0e-11e9-9b9b-50b31fe7af8f.png)

Details show that the vast majority is the `ByteArrayOutputStrem`, but we also have a considerably large ArrayList, containing JaCoCo classes, namely `PackageCoverageImpl` instances, which in turn contain lists of `ClassCoverageImpl`s and so on.

So we should at least try and get the bytes directly to disk, but we may also look whether we can get smarter with the `CoverageImpl` stuff.

**Comment by AnonymFx** [comment]
Only replacing the ByteArrayOutputStream with a FileOutputStream already reduces the memory footprint quite significantly.
![before](https://user-images.githubusercontent.com/5918583/65661703-9e47c100-e032-11e9-8e54-631b14b52c5a.png)
![after](https://user-images.githubusercontent.com/5918583/65661698-99830d00-e032-11e9-84e9-c7111de80366.png)
85.8 -> 28.7 => 66%

**Comment by karottenreibe** [comment]
Migrated as TS-21140
