### ISSUE TITLE
ParseGitProperties timestamp parse error for ISO 8601 time formats

### ISSUE THREAD

**Issue by ua4t4s0ft** [cqse/teamscale-jacoco-agent#464]
Hello CQSE Team,

We use the [git-commit-id-maven-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin) to generate the git.properties file. After a breaking change [#699](https://github.com/git-commit-id/git-commit-id-maven-plugin/pull/699) of the time format in [Version 8.0.0](https://github.com/git-commit-id/git-commit-id-maven-plugin/releases/tag/v8.0.0) the agent throws a DateTimeParseException for e.g. '2024-02-12T13:26:52+02:00' (see screenshot)

![image](https://github.com/cqse/teamscale-jacoco-agent/assets/170615046/8febd7b8-293e-4761-8e83-4867d20c3a23)

![image](https://github.com/cqse/teamscale-jacoco-agent/assets/170615046/9178b3d4-addc-48b7-b985-3b1083b98d47)

It would be very helpful if the agent also supported the new time format.

Best Uwe

**Comment by DreierF** [comment]
Thanks for taking the time to report the issue!
The agent already has an option `artifactory-git-properties-commit-date-format` that you can use to adjust the expected data format to e.g. `yyyy-MM-dd'T'HH:mm:ssXXX`. As this is the new default for the maven plugin we will be adjusting the agent to accept the new data format by default without additional configuration soon.

**Comment by RainerGanss** [comment]
Looking forward to that default ;-)

**Comment by AnonymFx** [comment]
Sometimes, there are nice coincidences 🙂 I was just touching the code for a different feature and already improved the date parsing logic in non-Artifactory scenarios. So the fix was quite easy to carry over to the Artifactory use case 🥳
