### ISSUE TITLE
Simpler Out-Of-The-Box setup

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-jacoco-agent#49]
Make it simpler for new users to get their first results in Teamscale.

Ideas:

- If class-dir is not set, use Jacoco's class dump dir parameter to dump classes to a temporary directory on disk and parse them from there during XML generation
- make the agent log errors in cases where it is clearly misconfigured, e.g.
  - trace file is empty
  - the include patterns match no code in the parsed class files
- example config file for the simplest possible use case with some comments explaining the different options

**Comment by Macariel** [comment]
Sorry for the long inactivity. I was almost done, but then I lost sight of it.
I'm kinda confused about the jacoco-verifier. You referenced the issue #60 which only mentions adding the verifier in the documentation, but it actually solves a few of the problems mentioned in hear:
- empty trace file
- include pattern not matching
I already have similar a solution for the empty trace file. 
Is the jacoco-verifier already included in some way or should I implement separate solutions for those problems?

**Comment by karottenreibe** [comment]
Correct. I created the verifier as a quick solution to check for common problems. In hindsight, it seemed even better to just include those checks in the agent which is why I created this ticket. Then I forgot about it and created #60 ;-)

So I'll discard #60 and you can integrate those checks into the agent.

**Comment by karottenreibe** [comment]
Migrated as TS-21139
