### ISSUE TITLE
Handle Teamscale URLs without slash at the end

### ISSUE THREAD

**Issue by karottenreibe** [cqse/teamscale-jacoco-agent#50]
Currently, when running the agent and providing a TS URL to upload to, it has to end in slash. Otherwise I get an exception saying "baseUrl must end in slash".

We should check if the baseUrl ends in a slash in the agent and add it ourselves if not (both if the value is read from the agent parameter and from the config file)

**Comment by Macariel** [comment]
I was about to close the issue, but apparently this issue only occurs if the url has a path.
