### ISSUE TITLE
Didn't work on Windows Server 2012 without setting java/bin in windows path

### ISSUE THREAD

**Issue by zipperle** [cqse/teamscale-jacoco-agent#66]
Reported by customer, no xml-files were created until the java/bin path was set in windows path

**Comment by karottenreibe** [comment]
The goal of this issue would be to try and replicate this by explicitly removing java/bin from the PATH under windows and checking if our profiler still works.

I think it should, so if it doesn't we need to find out why and fix this or at least document this requirement

**Comment by karottenreibe** [comment]
Discarding as not reproducible
