### ISSUE TITLE
Support for SAP NetWeaver Java

### ISSUE THREAD

**Issue by agoeb** [cqse/teamscale-jacoco-agent#93]
Since SAP NetWeaver Development Infrastructure (NWDI) has no easy way of adding additional modules to the build in order to add a commit timestamp directly to the MANIFEST.MF file, we need another way of figuring out the build version.

- Deployment is always triggered from whatever is in /dev/active in the Design Time Repository (DTR), so we know the "branch".
- The MANIFEST.MF of the deployed EAR file does already contain an entry `Implementation-Version` with a timestamp encoded as `yyyyMMddHHmmss` in UTC time, which would give us the commit timestamp

Also, you typically have a large NW Java instance running, with several (smaller) applications deployed to it, some of which may reside in different (DTR) repositories and, hence, different Teamscale projects, and which are deployed independently from each other. So, we need to be able to read several EAR files, parse their timestamps, and upload the coverage to several Teamscale projects, based on an additional configuration file. This should be in some file format that supports array- or list-style structures, like JSON or YAML. Then we could have one entry per Teamscale project.

One large NW Java server typically has a dedicated purpose, e.g. dev server, integration server, test, production. Hence, the partition name may be independent from the particular Teamscale project / EAR file, but set on the top level, just like the Teamscale URL and credentials (maybe just using the already existing config parameters).

When documenting the parameter, we may check for consistency with #92

**Comment by agoeb** [comment]
@DreierF is this something you could implement efficiently?

**Comment by karottenreibe** [comment]
Moved as TS-21136
